const api=async(path,options={})=>{const r=await fetch('/api'+path,options);if(!r.ok)throw Error((await r.json()).detail||r.statusText);return r.json()};
const content=document.querySelector('#content'),title=document.querySelector('#title');let current=null;
const bytes=n=>n>1e9?(n/1e9).toFixed(1)+' GB':n>1e6?(n/1e6).toFixed(1)+' MB':(n/1e3).toFixed(1)+' KB';
async function projects(){title.textContent='Projects';const rows=await api('/projects');content.innerHTML=rows.length?rows.map(p=>`<article class="card" data-id="${p.id}"><span class="status">${p.status}</span><h3>${p.name}</h3><div class="meta">${p.renderer} · Updated ${new Date(p.updated_at).toLocaleString()}</div></article>`).join(''):'<div class="empty">Create your first persistent avatar project.</div>';document.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>openProject(x.dataset.id))}
async function queue(){title.textContent='Render Queue';const rows=await api('/jobs');content.innerHTML=rows.length?rows.map(j=>{const a=j.renderer_activity;const live=j.state==='generating'&&a;const detail=live?`${a.message}${a.units_completed?` · ${a.units_completed} ${a.unit_name}`:''} · active ${new Date(a.reported_at).toLocaleTimeString()}`:j.state==='generating'?'Renderer active · exact progress unavailable':`Clip ${j.current_clip} / ${j.total_clips}`;return `<article class="card"><span class="status">${j.state}</span><h3>${live?a.stage.replaceAll('_',' '):j.phase}</h3>${live?'':`<div class="progress"><i style="width:${j.progress*100}%"></i></div>`}<p class="meta">${detail} · ${j.id}</p>${j.error?`<p>${j.error.split('\n')[0]}</p>`:''}</article>`}).join(''):'<div class="empty">No render jobs yet.</div>'}
async function files(){title.textContent='Files';const rows=await api('/files');content.innerHTML=rows.map(f=>`<article class="card"><h3>${f.path.split('/').pop()}</h3><div class="meta">${bytes(f.size)} · ${f.path}</div></article>`).join('')||'<div class="empty">Persistent storage is empty.</div>'}
async function system(){title.textContent='Diagnostics';const [health,sys,caches]=await Promise.all([api('/health'),api('/system'),api('/caches')]);content.innerHTML=`<article class="card"><span class="status">${health.status}</span><h3>Application ${health.version}</h3><pre>${JSON.stringify(sys,null,2)}</pre></article>${health.renderers.map(r=>`<article class="card"><span class="status">${r.available?'available':'degraded'}</span><h3>${r.capabilities.display_name}</h3><div class="meta">Recovery level ${r.capabilities.recovery_level}</div></article>`).join('')}${caches.map(c=>`<article class="card"><h3>${c.path}</h3><div class="meta">${bytes(c.size)}</div></article>`).join('')}`}
async function openProject(id){current=await api('/projects/'+id);editorTitle.textContent=current.name;prompt.value=current.prompt;assetState.textContent=current.assets.map(a=>`${a.kind}: ${a.original_name}`).join(' · ')||'Upload a portrait and audio';editor.showModal()}
newProject.onclick=async()=>{const rs=await api('/renderers');renderer.innerHTML=rs.map(r=>`<option value="${r.capabilities.name}">${r.capabilities.display_name}${r.available?'':' (models missing)'}</option>`).join('');createDialog.showModal()};
create.onclick=async e=>{e.preventDefault();const p=await api('/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:projectName.value,renderer:renderer.value})});createDialog.close();await projects();openProject(p.id)};
save.onclick=async e=>{e.preventDefault();await api('/projects/'+current.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:prompt.value})});for(const [kind,input] of [['portrait',portrait],['audio',audio]])if(input.files[0]){const f=new FormData();f.append('file',input.files[0]);await api(`/projects/${current.id}/${kind}`,{method:'POST',body:f})}await openProject(current.id)};
render.onclick=async e=>{e.preventDefault();await save.onclick(e);await api(`/projects/${current.id}/render`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});editor.close();show('queue')};
async function show(view){document.querySelectorAll('aside button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));await ({projects,queue,files,system})[view]()};document.querySelectorAll('aside button').forEach(x=>x.onclick=()=>show(x.dataset.view));
setInterval(()=>{if(title.textContent==='Render Queue')queue();api('/health').then(x=>health.textContent=x.status==='ok'?'System healthy':'Degraded').catch(()=>health.textContent='Offline')},3000);projects();
