const api=async(path,options={})=>{const r=await fetch('/api'+path,options);if(!r.ok)throw Error((await r.json()).detail||r.statusText);return r.json()};
const content=document.querySelector('#content'),title=document.querySelector('#title');let current=null;
const bytes=n=>n>1e9?(n/1e9).toFixed(1)+' GB':n>1e6?(n/1e6).toFixed(1)+' MB':(n/1e3).toFixed(1)+' KB';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function projects(){title.textContent='Projects';const rows=await api('/projects');content.innerHTML=rows.length?rows.map(p=>`<article class="card" data-id="${p.id}"><span class="status">${p.status}</span><h3>${p.name}</h3><div class="meta">${p.renderer} · Updated ${new Date(p.updated_at).toLocaleString()}</div></article>`).join(''):'<div class="empty">Create your first persistent avatar project.</div>';document.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>openProject(x.dataset.id))}
async function history(){title.textContent='Render History';const rows=await api('/history');content.innerHTML=rows.length?rows.map(item=>{const details=[item.duration&&`${item.duration.toFixed(1)}s`,item.width&&`${item.width}×${item.height}`,bytes(item.size)].filter(Boolean).join(' · ');const exported=item.export_download_url?`<a class="download secondary" href="${encodeURI(item.export_download_url)}" download>Download export</a>`:'';return `<article class="card history-card"><span class="status">${item.source}</span><h3>${esc(item.project_name)}</h3><div class="meta">${esc(item.filename)} · ${details}</div><div class="meta">${new Date(item.created_at).toLocaleString()}</div><div class="download-row"><a class="download" href="${encodeURI(item.download_url)}" download>Download video</a>${exported}</div></article>`}).join(''):'<div class="empty">No completed videos found in the database or exports folder.</div>'}
async function queue(){title.textContent='Render Queue';const rows=await api('/jobs');content.innerHTML=rows.length?rows.map(j=>{const a=j.renderer_activity;const live=j.state==='generating'&&a;const measured=live&&a.units_total;const percent=measured?Math.min(100,a.units_completed/a.units_total*100):j.progress*100;const eta=measured&&a.seconds_remaining!=null?` · about ${Math.ceil(a.seconds_remaining/60)} min remaining`:'';const detail=live?`${a.message}${measured?` · ${a.units_completed} / ${a.units_total} ${a.unit_name}`:''}${eta} · active ${new Date(a.reported_at).toLocaleTimeString()}`:j.state==='generating'?'Renderer active · exact progress unavailable':`Clip ${j.current_clip} / ${j.total_clips}`;return `<article class="card"><span class="status">${j.state}</span><h3>${live?a.stage.replaceAll('_',' '):j.phase}</h3><div class="progress"><i style="width:${percent}%"></i></div><p class="meta">${detail} · ${j.id}</p>${j.error?`<p>${j.error.split('\n')[0]}</p>`:''}</article>`}).join(''):'<div class="empty">No render jobs yet.</div>'}
async function files(){title.textContent='Files';const rows=await api('/files');content.innerHTML=rows.map(f=>`<article class="card"><h3>${f.path.split('/').pop()}</h3><div class="meta">${bytes(f.size)} · ${f.path}</div></article>`).join('')||'<div class="empty">Persistent storage is empty.</div>'}
async function system(){title.textContent='Diagnostics';const [health,sys,caches]=await Promise.all([api('/health'),api('/system'),api('/caches')]);content.innerHTML=`<article class="card"><span class="status">${health.status}</span><h3>Application ${health.version}</h3><pre>${JSON.stringify(sys,null,2)}</pre></article>${health.renderers.map(r=>`<article class="card"><span class="status">${r.available?'available':'degraded'}</span><h3>${r.capabilities.display_name}</h3><div class="meta">Recovery level ${r.capabilities.recovery_level}</div></article>`).join('')}${caches.map(c=>`<article class="card"><h3>${c.path}</h3><div class="meta">${bytes(c.size)}</div></article>`).join('')}`}
function showAnalysis(value){previewPanel.innerHTML=value?.preview_url?`<img src="${encodeURI(value.preview_url)}" alt="Normalized portrait preview">`:'';if(value&&!durationSeconds.value)durationSeconds.value=value.duration.toFixed(3);analysisState.textContent=value?`${value.render_plan.audio_duration.toFixed(2)} of ${value.duration.toFixed(2)} seconds · ${value.render_plan.number_of_clips} clips · ${value.render_plan.frames_per_clip} frames/clip at ${value.render_plan.effective_fps} FPS`:'Analyze assets to preview the normalized portrait and render plan.'}
let parameterSchema=[];
function drawControls(useDefaults=false){rendererControls.innerHTML=parameterSchema.map(p=>{const value=useDefaults?p.default:(current.renderer_settings[p.name]??p.default);const input=p.type==='select'?`<select data-setting="${p.name}">${p.options.map(x=>`<option${x===value?' selected':''}>${x}</option>`).join('')}</select>`:p.type==='boolean'?`<input data-setting="${p.name}" type="checkbox"${value?' checked':''}>`:`<div class="range-row"><input data-setting="${p.name}" type="range" min="${p.min}" max="${p.max}" step="${p.step}" value="${value}"><output>${value}</output></div>`;return `<label class="parameter"><span>${p.label}</span>${input}<small>${p.help} Default: ${p.default}.</small></label>`}).join('');rendererControls.querySelectorAll('input[type=range]').forEach(x=>x.oninput=()=>x.nextElementSibling.value=x.value)}
function readControls(){const values=Object.fromEntries(parameterSchema.map(p=>{const input=rendererControls.querySelector(`[data-setting="${p.name}"]`);const value=p.type==='boolean'?input.checked:p.type==='range'?Number(input.value):input.value;return [p.name,value]}));if(durationSeconds.value)values.duration_seconds=Number(durationSeconds.value);return values}
async function openProject(id){current=await api('/projects/'+id);const renderers=await api('/renderers');parameterSchema=renderers.find(x=>x.capabilities.name===current.renderer)?.capabilities.generation_parameters||[];editorTitle.textContent=current.name;prompt.value=current.prompt;durationSeconds.value=current.renderer_settings.duration_seconds??'';assetState.textContent=current.assets.map(a=>`${a.kind}: ${a.original_name}`).join(' · ')||'Upload a portrait and audio';drawControls();showAnalysis(current.analysis);if(!editor.open)editor.showModal()}
newProject.onclick=async()=>{const rs=await api('/renderers');renderer.innerHTML=rs.map(r=>`<option value="${r.capabilities.name}">${r.capabilities.display_name}${r.available?'':' (models missing)'}</option>`).join('');createDialog.showModal()};
create.onclick=async e=>{e.preventDefault();const p=await api('/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:projectName.value,renderer:renderer.value})});createDialog.close();await projects();openProject(p.id)};
save.onclick=async e=>{e.preventDefault();await api('/projects/'+current.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:prompt.value,renderer_settings:readControls()})});for(const [kind,input] of [['portrait',portrait],['style',styleReference],['audio',audio]])if(input.files[0]){const f=new FormData();f.append('file',input.files[0]);await api(`/projects/${current.id}/${kind}`,{method:'POST',body:f});input.value=''}await openProject(current.id)};
resetSettings.onclick=e=>{e.preventDefault();drawControls(true);durationSeconds.value=current.analysis?.duration?.toFixed(3)||''};
analyze.onclick=async e=>{e.preventDefault();await save.onclick(e);analysisState.textContent='Analyzing audio and normalizing portrait…';const result=await api(`/projects/${current.id}/analyze`,{method:'POST'});current.analysis=result;showAnalysis(result)};
render.onclick=async e=>{e.preventDefault();await save.onclick(e);await api(`/projects/${current.id}/render`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});editor.close();show('queue')};
async function show(view){document.querySelectorAll('aside button').forEach(x=>x.classList.toggle('active',x.dataset.view===view));await ({projects,history,queue,files,system})[view]()};document.querySelectorAll('aside button').forEach(x=>x.onclick=()=>show(x.dataset.view));
setInterval(()=>{if(title.textContent==='Render Queue')queue();api('/health').then(x=>health.textContent=x.status==='ok'?'System healthy':'Degraded').catch(()=>health.textContent='Offline')},3000);projects();
